"""Added account table

Revision ID: c5bb62bc126c
Revises: 
Create Date: 2023-04-08 10:31:17.652424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c5bb62bc126c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bets",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEW", "FINISHED_WIN", "FINISHED_LOSE", name="status"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bets_event_id"), "bets", ["event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bets_event_id"), table_name="bets")
    op.drop_table("bets")
    # ### end Alembic commands ###
